name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Orbiter
        uses: orbiterhost/orbiter-github-actions@v0.1.0
        with:
          project-name: "ploan"
          build-dir: "./out"
          api-key: ${{ secrets.ORBITER_API_KEY }}
          node-version: "20.x"
          build-command: "pnpm run build"
